import sys
import os
import json

# Add parent directory to path to allow importing from src
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.core import (
    compile_rule,
    compile_scroll_rule,
    ButtonConfig,
    ButtonBehavior,
    Action
)

# --- HARDWARE CONSTANTS ---
# We hardcode the IDs here to strictly target your specific device.
VERBATIM_VENDOR_ID = 0x68e
VERBATIM_PRODUCT_ID = 0xb5

def generate_scroll_profile():
    """
    Generates a complete Karabiner profile for the Verbatim mouse.

    Features tested:
    1. Button 1 (Dual Role): Tap for '1', Hold for 'gesture_mode'.
    2. Scroll Up (Layered): Emulates 'Control + Left Arrow' (Move Space Left).
    3. Scroll Down (Layered): Emulates 'Control + Right Arrow' (Move Space Right).
    """
    print(f"Generating Scroll Profile for Device: {hex(VERBATIM_VENDOR_ID)} / {hex(VERBATIM_PRODUCT_ID)}")

    rules = []

    # -------------------------------------------------------------------------
    # 1. DEFINE THE TRIGGER (Physical Button 1)
    # -------------------------------------------------------------------------
    # This button activates the 'gesture_mode' variable when held.
    trigger_btn = ButtonConfig(
        button_id="1",
        behavior=ButtonBehavior.DUAL,
        tap_action=Action(key_code="1"),
        layer_variable="gesture_mode",
        threshold_ms=200
    )

    # Compile the trigger rule using the Core
    rules.append(compile_rule(trigger_btn, VERBATIM_VENDOR_ID, VERBATIM_PRODUCT_ID))

    # -------------------------------------------------------------------------
    # 2. DEFINE SCROLL UP BEHAVIOR
    # -------------------------------------------------------------------------
    # Logic: When 'gesture_mode' is 1 AND User Scrolls UP -> Switch Desktop Left
    action_scroll_up = Action(
        key_code="left_arrow",
        modifiers=["left_control"]
    )

    rule_scroll_up = compile_scroll_rule(
        vendor_id=VERBATIM_VENDOR_ID,
        product_id=VERBATIM_PRODUCT_ID,
        layer_name="gesture_mode",
        scroll_direction="up",
        target_action=action_scroll_up
    )
    rules.append(rule_scroll_up)

    # -------------------------------------------------------------------------
    # 3. DEFINE SCROLL DOWN BEHAVIOR
    # -------------------------------------------------------------------------
    # Logic: When 'gesture_mode' is 1 AND User Scrolls DOWN -> Switch Desktop Right
    action_scroll_down = Action(
        key_code="right_arrow",
        modifiers=["left_control"]
    )

    rule_scroll_down = compile_scroll_rule(
        vendor_id=VERBATIM_VENDOR_ID,
        product_id=VERBATIM_PRODUCT_ID,
        layer_name="gesture_mode",
        scroll_direction="down",
        target_action=action_scroll_down
    )
    rules.append(rule_scroll_down)

    # -------------------------------------------------------------------------
    # OUTPUT GENERATION
    # -------------------------------------------------------------------------
    final_profile = {
        "title": "MouseMapper: Scroll Gesture Test",
        "rules": [
            {
                "description": "Generated by test_scroll_implementation.py",
                "manipulators": rules
            }
        ]
    }

    print(json.dumps(final_profile, indent=2))

if __name__ == "__main__":
    generate_scroll_profile()
